include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    one_member_abstracts: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/messages_all.dart"
    - "**/messages_en.dart"
    - "**/messages_ru.dart"
    - "**/l10n.dart"
