name: tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  equatable: ^2.0.5
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.5.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  intl: ^0.19.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.21.2
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
